name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable, nightly]
        os: [ubuntu-20.04, windows-2019, macos-12, macos-14]
        type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      run: rustup toolchain install ${{ matrix.rust }} --profile minimal --component rustfmt clippy

    - name: Install Dependencies (Linux)
      run: sudo apt-get update && sudo apt-get install libpulse-dev pulseaudio libdbus-1-dev
      if: matrix.os == 'ubuntu-20.04'

    - name: Check format
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo fmt -- --check

    - name: Clippy
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo clippy -- -D warnings

    - name: Build
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo build --all

    - name: Test
      shell: bash
      run: rustup run ${{ matrix.rust }} cargo test --all
      # ubuntu setrlimit64 error in the CI container, macos not supported
      if: >
        matrix.os != 'ubuntu-20.04'
        && matrix.os != 'macos-12' && matrix.os != 'macos-14'
